name: resnet
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.5.1 # or the version you want.
  - torchvision=0.20.1 # or the version you want.
  - torchaudio=2.5.1 # or the version you want.
  - streamlit
