name: resnet
channels:
  - pytorch
  - conda-forge # Added conda-forge
  - defaults
dependencies:
  - python=3.9  # Specify Python version
  - pytorch=2.5.1 # Or latest if you want.
  - torchvision=0.20.1 # Or latest if you want.
  - torchaudio=2.5.1 # Or latest if you want.
  - cpuonly # Remove if using a GPU
  - anyio # Removed version constraint
  - argon2-cffi=21.3.0
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - debugpy=1.8.11
  - exceptiongroup=1.2.0
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.15.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonschema=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.4
  - lcms2=2.16
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.26.4
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtconsole=5.6.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=75.1.0
  - soupsieve=2.5
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - zipp=3.21.0
  - pip:
      - absl-py==2.1.0
      - altair==5.5.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - click==8.1.8
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.69.0
      - importlib-metadata==8.6.1
      - markdown==3.7
      - monai==1.4.0
      - narwhals==1.29.1
      - nibabel==5.3.2
      - pandas==2.2.3
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pytz==2025.1
      - smmap==5.0.2
      - streamlit==1.43.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - toml==0.10.2
      - tqdm==4.67.1
      - tzdata==2025.1
      - watchdog==6.0.0
      - werkzeug==3.1.3
